### ISSUE TITLE
Don't leak memory when using Libc.malloc?

### ISSUE THREAD

**Issue by nstiurca** [RelationalAI-oss/Blobs.jl#11]
From what I can tell, `Blobs.malloc()` and friends are very prone to leaking memory. Perhaps the returned blobs should be wrapped with something like `finalizer(Blobs.free, blob)`?

**Comment by tjgreen** [comment]
`Blobs.malloc()` is there mainly for the convenience of tests; the idea with the package is that memory management is done somewhere else, and the `Blobs` infrastructure just lets you interpret and modify the bits of the memory at a higher level (and with bounds-checking).

**Comment by nstiurca** [comment]
Fair enough. Feel free to just close this then.
